FROM ubuntu:22.04 as build

RUN apt-get update
RUN apt-get -y install make gcc=4:11.2.0-1ubuntu1

WORKDIR /opt/queen

COPY ./queen/inc/ inc
COPY ./queen/src/ src
COPY ./queen/Makefile Makefile

RUN make queen.exe



FROM ubuntu:22.04

COPY --from=build /opt/queen/queen.exe /bin/queen.exe

CMD ["queen.exe"]
