FROM ubuntu:22.04 as build

RUN apt-get update
RUN apt-get -y install make gcc=4:11.2.0-1ubuntu1

WORKDIR /opt/emmet

COPY ./emmet/inc/ inc
COPY ./emmet/src/ src
COPY ./emmet/Makefile Makefile

RUN make emmet.exe



FROM ubuntu:22.04

COPY --from=build /opt/emmet/emmet.exe /bin/emmet.exe

CMD ["emmet.exe"]
