version: '3.8'

services:
  emmet:
    build:
      dockerfile: Dockerfile.emmet
    command: emmet.exe -p 12345
    expose:
      - 12345/udp

  queen:
    build:
      dockerfile: Dockerfile.queen
    command: queen.exe -p 12345
    depends_on:
      - emmet
# 172.21.0.0/16

