version: '3.8'

services:
  emmet:
    build:
      dockerfile: Dockerfile.emmet
    command: emmet.exe

  queen:
    build:
      dockerfile: Dockerfile.queen
    environment:
      - INPUT_FILE=${INPUT_FILE:-sample100M.txt}}
    command: bash -c "cat /data/$INPUT_FILE | queen.exe -d 1048576 > /opt/out/result.txt"
    depends_on:
      - emmet
    volumes:
      - ./data:/data:ro
      - ./out:/opt/out/:rw
